server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter

        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthFilter

        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/order/**
          filters:
            - AuthFilter

        - id: authentication
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
jwt:
  secret: 4c91c9aaaceb49c27e876aae901a5b0c955e0c698349fd10d86cc9234a32e91
